### ISSUE TITLE
Active parent entries

### ISSUE THREAD

**Issue by ilazaridis** [designspike/bolt-extension-menuchain#1]
I have this menu:
- Item 1
  - Subitem 1.1
- Item 2
  - Subitem 2.1
  - Subitem 2.2
- Item 3
  - Subitem 3.1

When a subitem is active, for example subitem 2.1, I want the parent item (Item 2) to be active as well.
This extension solves this problem, but I don't understand how exactly. menuchain_urls will highlight every parent item (Item 1, Item 2, Item 3) in my case.
@use

**Comment by use** [comment]
Hi, can you show an example of how you are using the code in your template?
