### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Notice: Undefined index: link")

### ISSUE THREAD

**Issue by Mahan-F** [designspike/bolt-extension-menuchain#2]
I have installed the menuchain extension on my bolt website and I tried to use it. I copy/pasted code from the documentation and I got an error.

Code I have on my template:
```
{% set menuchain = menuchain_nodes('main', app.request.getPathInfo()) %}
```

Error: https://i.scrny.me/4XfY.png

I am using bolt version `3.4.6` and menuchain version `2.0.2`

**Comment by use** [comment]
Hi Mahan, looks like what's happening is it's expecting to find the 'link' index but Bolt didn't supply it for some reason.

Any chance I can see the menu.yml as well as the slug of the resource being requested, like for example /pages/mycooltestpage ? This way I can test and see if I can recreate the problem and make the appropriate patch to the extension.

**Comment by Mahan-F** [comment]
Hi Will, I was just about to update this issue, I found the problem. I have dropdowns on my menu and for the parents I did not put anything for "path" because they shouldn't redirect to anywhere. Right now I just changed all those menu items' path to be "/" and it fixed the problem, maybe the extension can check if something is given for path and if not it will set it to be # for the link?

**Comment by use** [comment]
Thanks for the feedback, I think you're right that it shouldn't just fail in that case, it should instead ignore that node and carry on. I will put that on the todo list!
